// Автоматически сгенерировано из прайс-листа. Обновляйте при изменении ассортимента.
const PRODUCTS = [
  {
    "id": 1,
    "category": "Вино",
    "country": "Грузия",
    "brand": "Kartuli Marani",
    "name": "Вино белое полусладкое Алазанская долина Kartuli Marani",
    "volume": 0.75,
    "minOrder": 6,
    "price": 2460,
    "image": "images/1.jpg"
  },
  {
    "id": 2,
    "category": "Вино",
    "country": "Грузия",
    "brand": "Kartuli Marani",
    "name": "Вино красное полусладкое Алазанская долина Kartuli Marani",
    "volume": 0.75,
    "minOrder": 6,
    "price": 2750,
    "image": "images/2.jpg"
  },
  {
    "id": 3,
    "category": "Вино",
    "country": "Грузия",
    "brand": "Kartuli Marani",
    "name": "Вино розовое полусладкое Алазанская долина Kartuli Marani",
    "volume": 0.75,
    "minOrder": 6,
    "price": 2710,
    "image": "images/3.jpg"
  },
  {
    "id": 4,
    "category": "Вино",
    "country": "Грузия",
    "brand": "Kartuli Marani",
    "name": "Вино красное полусладкое Ахашени Kartuli Marani",
    "volume": 0.75,
    "minOrder": 6,
    "price": 3800,
    "image": "images/4.jpg"
  },
  {
    "id": 5,
    "category": "Вино",
    "country": "Грузия",
    "brand": "Kartuli Marani",
    "name": "Вино красное полусладкое Киндзмараули Kartuli Marani",
    "volume": 0.75,
    "minOrder": 6,
    "price": 4130,
    "image": "images/5.jpg"
  },
  {
    "id": 6,
    "category": "Вино",
    "country": "Грузия",
    "brand": "Kartuli Marani",
    "name": "Вино красное сухое Мукузани Kartuli Marani",
    "volume": 0.75,
    "minOrder": 6,
    "price": 4300,
    "image": "images/6.jpg"
  },
  {
    "id": 7,
    "category": "Вино",
    "country": "Грузия",
    "brand": "Kartuli Marani",
    "name": "Вино красное полусладкое Оджалеши Kartuli Marani",
    "volume": 0.75,
    "minOrder": 6,
    "price": 5050,
    "image": "images/7.jpg"
  },
  {
    "id": 8,
    "category": "Вино",
    "country": "Грузия",
    "brand": "Kartuli Marani",
    "name": "Вино белое полусухое Пиросмани Kartuli Marani",
    "volume": 0.75,
    "minOrder": 6,
    "price": 2550,
    "image": "images/8.jpg"
  },
  {
    "id": 9,
    "category": "Вино",
    "country": "Грузия",
    "brand": "Kartuli Marani",
    "name": "Вино красное полусухое Пиросмани Kartuli Marani",
    "volume": 0.75,
    "minOrder": 6,
    "price": 2840,
    "image": "images/9.jpg"
  },
  {
    "id": 10,
    "category": "Вино",
    "country": "Грузия",
    "brand": "Kartuli Marani",
    "name": "Вино красное сухое Саперави Kartuli Marani",
    "volume": 0.75,
    "minOrder": 6,
    "price": 3130,
    "image": "images/10.jpg"
  },
  {
    "id": 11,
    "category": "Вино",
    "country": "Грузия",
    "brand": "Kartuli Marani",
    "name": "Вино белое полусладкое Твиши Kartuli Marani",
    "volume": 0.75,
    "minOrder": 6,
    "price": 5170,
    "image": "images/11.jpg"
  },
  {
    "id": 12,
    "category": "Вино",
    "country": "Грузия",
    "brand": "Kartuli Marani",
    "name": "Вино красное полусладкое Хванчкара Kartuli Marani",
    "volume": 0.75,
    "minOrder": 6,
    "price": 8250,
    "image": "images/12.jpg"
  },
  {
    "id": 13,
    "category": "Вино",
    "country": "Грузия",
    "brand": "Kartuli Marani",
    "name": "Вино белое сухое Цинандали Kartuli Marani",
    "volume": 0.75,
    "minOrder": 6,
    "price": 3000,
    "image": "images/13.jpg"
  },
  {
    "id": 14,
    "category": "Вино",
    "country": "Грузия",
    "brand": "Winiveria",
    "name": "Вино красное полусладкое Киндзмараули Winiveria",
    "volume": 0.75,
    "minOrder": 6,
    "price": 6460,
    "image": "images/14.jpg"
  },
  {
    "id": 15,
    "category": "Вино",
    "country": "Грузия",
    "brand": "Winiveria",
    "name": "Вино белое полусладкое Киси Winiveria",
    "volume": 0.75,
    "minOrder": 6,
    "price": 5750,
    "image": "images/15.jpg"
  },
  {
    "id": 16,
    "category": "Вино",
    "country": "Грузия",
    "brand": "Winiveria",
    "name": "Вино красное сухое Мукузани Winiveria",
    "volume": 0.75,
    "minOrder": 6,
    "price": 6380,
    "image": "images/16.jpg"
  },
  {
    "id": 17,
    "category": "Вино",
    "country": "Грузия",
    "brand": "Winiveria",
    "name": "Вино белое сухое Мцвани Winiveria",
    "volume": 0.75,
    "minOrder": 6,
    "price": 5550,
    "image": "images/17.jpg"
  },
  {
    "id": 18,
    "category": "Вино",
    "country": "Грузия",
    "brand": "Winiveria",
    "name": "Вино белое сухое Ркацители Winiveria",
    "volume": 0.75,
    "minOrder": 6,
    "price": 5130,
    "image": "images/18.jpg"
  },
  {
    "id": 19,
    "category": "Вино",
    "country": "Грузия",
    "brand": "Winiveria",
    "name": "Вино красное сухое Саперави Winiveria",
    "volume": 0.75,
    "minOrder": 6,
    "price": 5710,
    "image": "images/19.jpg"
  },
  {
    "id": 20,
    "category": "Вино",
    "country": "Грузия",
    "brand": "Winiveria",
    "name": "Вино красное полусладкое Хванчкара Winiveria",
    "volume": 0.75,
    "minOrder": 6,
    "price": 13750,
    "image": "images/20.jpg"
  },
  {
    "id": 21,
    "category": "Вино",
    "country": "Грузия",
    "brand": "Winiveria",
    "name": "Вино белое сухое Хихви Winiveria",
    "volume": 0.75,
    "minOrder": 6,
    "price": 5840,
    "image": "images/21.jpg"
  },
  {
    "id": 22,
    "category": "Вино",
    "country": "Грузия",
    "brand": "Winiveria",
    "name": "Вино белое сухое Цинандали Winiveria",
    "volume": 0.75,
    "minOrder": 6,
    "price": 5550,
    "image": "images/22.jpg"
  },
  {
    "id": 23,
    "category": "Вино",
    "country": "Грузия",
    "brand": "Winiveria",
    "name": "Вино розовое полусухое Френч Winiveria",
    "volume": 0.75,
    "minOrder": 6,
    "price": 5750,
    "image": "images/23.jpg"
  },
  {
    "id": 24,
    "category": "Вино",
    "country": "Италия",
    "brand": "Tralcio",
    "name": "Вино белое сухое Tralcio Bianko",
    "volume": 5,
    "minOrder": 2,
    "price": 11090,
    "image": "images/24.jpg"
  },
  {
    "id": 25,
    "category": "Вино",
    "country": "Италия",
    "brand": "Tralcio",
    "name": "Вино белое полусладкое Tralcio Bianko semi sweet",
    "volume": 5,
    "minOrder": 2,
    "price": 12090,
    "image": "images/25.jpg"
  },
  {
    "id": 26,
    "category": "Вино",
    "country": "Италия",
    "brand": "Tralcio",
    "name": "Вино красное сухое Tralcio Rosso",
    "volume": 5,
    "minOrder": 2,
    "price": 11090,
    "image": "images/26.jpg"
  },
  {
    "id": 27,
    "category": "Вино",
    "country": "Италия",
    "brand": "Tralcio",
    "name": "Вино красное полусладкое Tralcio Rosso semi sweet",
    "volume": 5,
    "minOrder": 2,
    "price": 12090,
    "image": "images/27.jpg"
  },
  {
    "id": 28,
    "category": "Вино",
    "country": "Италия",
    "brand": "Casa Defra",
    "name": "Вино красное сухое Amarone Casa Defra",
    "volume": 0.75,
    "minOrder": 6,
    "price": 17880,
    "image": "images/28.jpg"
  },
  {
    "id": 29,
    "category": "Вино",
    "country": "Италия",
    "brand": "Casa Defra",
    "name": "Вино красное сухое Cabernet Sauvignon Casa Defra",
    "volume": 0.75,
    "minOrder": 6,
    "price": 4090,
    "image": "images/29.jpg"
  },
  {
    "id": 30,
    "category": "Вино",
    "country": "Италия",
    "brand": "Casa Defra",
    "name": "Вино белое сухое Chardonnay Casa Defra",
    "volume": 0.75,
    "minOrder": 6,
    "price": 4500,
    "image": "images/30.jpg"
  },
  {
    "id": 31,
    "category": "Вино",
    "country": "Италия",
    "brand": "Casa Defra",
    "name": "Вино красное сухое Merlot Casa Defra",
    "volume": 0.75,
    "minOrder": 6,
    "price": 4090,
    "image": "images/31.jpg"
  },
  {
    "id": 32,
    "category": "Вино",
    "country": "Италия",
    "brand": "Casa Defra",
    "name": "Вино белое сухое Pinot Grigio Casa Defra",
    "volume": 0.75,
    "minOrder": 6,
    "price": 4500,
    "image": "images/32.jpg"
  },
  {
    "id": 33,
    "category": "Вино",
    "country": "Италия",
    "brand": "Casa Defra",
    "name": "Вино розовое сухое Rose Blush Pinot Grigio Casa Defra",
    "volume": 0.75,
    "minOrder": 6,
    "price": 4500,
    "image": "images/33.jpg"
  },
  {
    "id": 34,
    "category": "Вино",
    "country": "Италия",
    "brand": "Freschello",
    "name": "Вино белое полусухое Freschello Bianco",
    "volume": 0.75,
    "minOrder": 6,
    "price": 3170,
    "image": "images/34.jpg"
  },
  {
    "id": 35,
    "category": "Вино",
    "country": "Италия",
    "brand": "Freschello",
    "name": "Вино белое полусладкое Freschello Bianco",
    "volume": 0.75,
    "minOrder": 6,
    "price": 3170,
    "image": "images/35.jpg"
  },
  {
    "id": 36,
    "category": "Вино",
    "country": "Италия",
    "brand": "Freschello",
    "name": "Вино розовое полусухое Freschello Rose",
    "volume": 0.75,
    "minOrder": 6,
    "price": 3170,
    "image": "images/36.jpg"
  },
  {
    "id": 37,
    "category": "Вино",
    "country": "Италия",
    "brand": "Freschello",
    "name": "Вино красное полусухое Freschello Rosso",
    "volume": 0.75,
    "minOrder": 6,
    "price": 3170,
    "image": "images/37.jpg"
  },
  {
    "id": 38,
    "category": "Вино",
    "country": "Италия",
    "brand": "Freschello",
    "name": "Вино красное полусладкое Freschello Rosso",
    "volume": 0.75,
    "minOrder": 6,
    "price": 3170,
    "image": "images/38.jpg"
  },
  {
    "id": 39,
    "category": "Вино",
    "country": "Италия",
    "brand": "Freschello",
    "name": "Вино красное сухое Gran Bericanto Riserva",
    "volume": 0.75,
    "minOrder": 6,
    "price": 10000,
    "image": "images/39.jpg"
  },
  {
    "id": 40,
    "category": "Вино",
    "country": "Италия",
    "brand": "Terre di Mario",
    "name": "Вино белое полусухое Terre di Mario Bianco",
    "volume": 0.75,
    "minOrder": 6,
    "price": 3750,
    "image": "images/40.jpg"
  },
  {
    "id": 41,
    "category": "Вино",
    "country": "Италия",
    "brand": "Terre di Mario",
    "name": "Вино красное сухое Terre di Mario Montepulciano d’Abruzzo",
    "volume": 0.75,
    "minOrder": 6,
    "price": 4090,
    "image": "images/41.jpg"
  },
  {
    "id": 42,
    "category": "Вино",
    "country": "Италия",
    "brand": "Terre di Mario",
    "name": "Вино белое сухое Terre di Mario Pinot Grigio d’Abruzzo",
    "volume": 0.75,
    "minOrder": 6,
    "price": 4090,
    "image": "images/42.jpg"
  },
  {
    "id": 43,
    "category": "Вино",
    "country": "Италия",
    "brand": "Terre di Mario",
    "name": "Вино красное полусухое Terre di Mario Rosso",
    "volume": 0.75,
    "minOrder": 6,
    "price": 3750,
    "image": "images/43.jpg"
  },
  {
    "id": 44,
    "category": "Вино",
    "country": "Италия",
    "brand": "Capo Zafferano",
    "name": "Вино красное полусухое Primitivo Puglia Capo Zafferano",
    "volume": 0.75,
    "minOrder": 6,
    "price": 7090,
    "image": "images/44.jpg"
  },
  {
    "id": 45,
    "category": "Вино",
    "country": "Италия",
    "brand": "Capo Zafferano",
    "name": "Вино красное сухое Negroamaro Puglia Capo Zafferano",
    "volume": 0.75,
    "minOrder": 6,
    "price": 7090,
    "image": "images/45.jpg"
  },
  {
    "id": 46,
    "category": "Вино",
    "country": "Италия",
    "brand": "Capo Zafferano",
    "name": "Вино красное сухое Primitivo di Manduria Capo Zafferano",
    "volume": 0.75,
    "minOrder": 6,
    "price": 8340,
    "image": "images/46.jpg"
  },
  {
    "id": 47,
    "category": "Вино",
    "country": "Италия",
    "brand": "Scantianum",
    "name": "Вино красное сухое Sangiovese Scantianum",
    "volume": 0.75,
    "minOrder": 6,
    "price": 5420,
    "image": "images/47.jpg"
  },
  {
    "id": 48,
    "category": "Вино",
    "country": "Италия",
    "brand": "Scantianum",
    "name": "Вино белое сухое Vermentino Toscana Scantianum",
    "volume": 0.75,
    "minOrder": 6,
    "price": 5420,
    "image": "images/48.jpg"
  },
  {
    "id": 49,
    "category": "Вино",
    "country": "Италия",
    "brand": "Scantianum",
    "name": "Вино красное сухое Sangiovese Toscano Vin del Fattore",
    "volume": 0.75,
    "minOrder": 6,
    "price": 6670,
    "image": "images/49.jpg"
  },
  {
    "id": 50,
    "category": "Вино",
    "country": "Франция",
    "brand": "Lafage",
    "name": "Вино белое сухое Miraflors Lafabuleuse Lafage",
    "volume": 0.75,
    "minOrder": 6,
    "price": 8340,
    "image": "images/50.jpg"
  },
  {
    "id": 51,
    "category": "Вино",
    "country": "Франция",
    "brand": "Lafage",
    "name": "Вино красное сухое Lafage Narassa",
    "volume": 0.75,
    "minOrder": 6,
    "price": 12500,
    "image": "images/51.jpg"
  },
  {
    "id": 52,
    "category": "Вино",
    "country": "Франция",
    "brand": "Lafage",
    "name": "Вино красное сухое Nicolas Lafage",
    "volume": 0.75,
    "minOrder": 6,
    "price": 10000,
    "image": "images/52.jpg"
  },
  {
    "id": 53,
    "category": "Вино",
    "country": "Франция",
    "brand": "Lafage",
    "name": "Вино белое сухое Novellum Lafage",
    "volume": 0.75,
    "minOrder": 6,
    "price": 8340,
    "image": "images/53.jpg"
  },
  {
    "id": 54,
    "category": "Вино",
    "country": "Франция",
    "brand": "Beauvignac",
    "name": "Вино белое сухое Chardonnay Beauvignac",
    "volume": 0.75,
    "minOrder": 6,
    "price": 5250,
    "image": "images/54.jpg"
  },
  {
    "id": 55,
    "category": "Вино",
    "country": "Франция",
    "brand": "Beauvignac",
    "name": "Вино красное сухое Cabernet Sauvignon Beauvignac",
    "volume": 0.75,
    "minOrder": 6,
    "price": 4920,
    "image": "images/55.jpg"
  },
  {
    "id": 56,
    "category": "Вино",
    "country": "Франция",
    "brand": "Beauvignac",
    "name": "Вино белое полусладкое Le Moelleux Blanc Beauvignac",
    "volume": 0.75,
    "minOrder": 6,
    "price": 4920,
    "image": "images/56.jpg"
  },
  {
    "id": 57,
    "category": "Вино",
    "country": "Франция",
    "brand": "Beauvignac",
    "name": "Вино красное сухое Merlot Beauvignac",
    "volume": 0.75,
    "minOrder": 6,
    "price": 4920,
    "image": "images/57.jpg"
  },
  {
    "id": 58,
    "category": "Вино",
    "country": "Франция",
    "brand": "Beauvignac",
    "name": "Вино белое сухое Sauvignnon Blanc Beauvignac",
    "volume": 0.75,
    "minOrder": 6,
    "price": 4750,
    "image": "images/58.jpg"
  },
  {
    "id": 59,
    "category": "Вино",
    "country": "Франция",
    "brand": "Beauvignac",
    "name": "Вино красное сухое Syrah Beauvignac",
    "volume": 0.75,
    "minOrder": 6,
    "price": 4920,
    "image": "images/59.jpg"
  },
  {
    "id": 60,
    "category": "Вино",
    "country": "Франция",
    "brand": "Beauvignac",
    "name": "Вино красное сухое Vin D'une Nuit Beauvignac",
    "volume": 0.75,
    "minOrder": 6,
    "price": 4750,
    "image": "images/60.jpg"
  },
  {
    "id": 61,
    "category": "Виски",
    "country": "Ирландия",
    "brand": "Kinahans",
    "name": "Виски Kinahans LL",
    "volume": 0.7,
    "minOrder": 6,
    "price": 11000,
    "image": "images/61.jpg"
  },
  {
    "id": 62,
    "category": "Виски",
    "country": "Ирландия",
    "brand": "Kinahans",
    "name": "Виски Kinahans LL GB",
    "volume": 0.7,
    "minOrder": 6,
    "price": 12090,
    "image": "images/62.jpg"
  },
  {
    "id": 63,
    "category": "Виски",
    "country": "Ирландия",
    "brand": "Kinahans",
    "name": "Виски Kinahans Small Batch",
    "volume": 0.7,
    "minOrder": 6,
    "price": 16920,
    "image": "images/63.jpg"
  },
  {
    "id": 64,
    "category": "Виски",
    "country": "Ирландия",
    "brand": "Kinahans",
    "name": "Виски Kinahans Special Release Project 18 Merlot",
    "volume": 0.7,
    "minOrder": 6,
    "price": 68340,
    "image": "images/64.jpg"
  },
  {
    "id": 65,
    "category": "Виски",
    "country": "Ирландия",
    "brand": "Kinahans",
    "name": "Виски Kinahans Special Release Project 28 Amarone",
    "volume": 0.7,
    "minOrder": 6,
    "price": 68340,
    "image": "images/65.jpg"
  },
  {
    "id": 66,
    "category": "Виски",
    "country": "Ирландия",
    "brand": "Kinahans",
    "name": "Виски Kinahans Special Release Project 08 Black Oak",
    "volume": 0.7,
    "minOrder": 6,
    "price": 70840,
    "image": "images/66.jpg"
  },
  {
    "id": 67,
    "category": "Виски",
    "country": "Ирландия",
    "brand": "Kinahans",
    "name": "Виски Kinahans SRP №04 QUADRAT CASK GT",
    "volume": 0.7,
    "minOrder": 6,
    "price": 70840,
    "image": "images/67.jpg"
  },
  {
    "id": 68,
    "category": "Виски",
    "country": "Ирландия",
    "brand": "Kinahans",
    "name": "Виски Kinahans Single Malt Heritage Whiskey",
    "volume": 0.7,
    "minOrder": 6,
    "price": 22090,
    "image": "images/68.jpg"
  },
  {
    "id": 69,
    "category": "Виски",
    "country": "Ирландия",
    "brand": "Kinahans",
    "name": "Виски Kinahans Single Malt Heritage Whiskey GT",
    "volume": 0.7,
    "minOrder": 6,
    "price": 23340,
    "image": "images/69.jpg"
  },
  {
    "id": 70,
    "category": "Виски",
    "country": "Ирландия",
    "brand": "Kinahans",
    "name": "Виски Kinahans Kasc Project (B) + 2 стакана",
    "volume": 0.7,
    "minOrder": 6,
    "price": 25000,
    "image": "images/70.jpg"
  },
  {
    "id": 71,
    "category": "Виски",
    "country": "Ирландия",
    "brand": "Lambay",
    "name": "Виски Lambay Single Grain",
    "volume": 0.7,
    "minOrder": 6,
    "price": 15000,
    "image": "images/71.jpg"
  },
  {
    "id": 72,
    "category": "Виски",
    "country": "Ирландия",
    "brand": "Lambay",
    "name": "Виски Lambay Small Batch Blend",
    "volume": 0.7,
    "minOrder": 6,
    "price": 19170,
    "image": "images/72.jpg"
  },
  {
    "id": 73,
    "category": "Виски",
    "country": "Ирландия",
    "brand": "Lambay",
    "name": "Виски Lambay Malt Irish",
    "volume": 0.7,
    "minOrder": 6,
    "price": 33340,
    "image": "images/73.jpg"
  },
  {
    "id": 74,
    "category": "Водка",
    "country": "Россия",
    "brand": "Gastronom",
    "name": "Водка Gastronom Купаж №1 Classic",
    "volume": 0.5,
    "minOrder": 6,
    "price": 4920,
    "image": "images/74.jpg"
  },
  {
    "id": 75,
    "category": "Водка",
    "country": "Россия",
    "brand": "Gastronom",
    "name": "Водка Gastronom Купаж №1 Classic",
    "volume": 0.7,
    "minOrder": 6,
    "price": 6590,
    "image": "images/75.jpg"
  },
  {
    "id": 76,
    "category": "Водка",
    "country": "Россия",
    "brand": "Gastronom",
    "name": "Водка Gastronom Купаж №7 к мясу",
    "volume": 0.5,
    "minOrder": 6,
    "price": 4920,
    "image": "images/76.jpg"
  },
  {
    "id": 77,
    "category": "Водка",
    "country": "Россия",
    "brand": "Gastronom",
    "name": "Водка Gastronom Купаж №4 к рыбе",
    "volume": 0.5,
    "minOrder": 6,
    "price": 4920,
    "image": "images/77.jpg"
  },
  {
    "id": 78,
    "category": "Водка",
    "country": "Россия",
    "brand": "Remeslo",
    "name": "Водка Ремесло",
    "volume": 0.5,
    "minOrder": 6,
    "price": 3250,
    "image": "images/78.jpg"
  },
  {
    "id": 79,
    "category": "Водка",
    "country": "Украина",
    "brand": "Celsius",
    "name": "Водка особая Celsius Ice",
    "volume": 0.5,
    "minOrder": 6,
    "price": 2920,
    "image": "images/79.jpg"
  },
  {
    "id": 80,
    "category": "Водка",
    "country": "Украина",
    "brand": "Celsius",
    "name": "Водка особая Celsius Ice",
    "volume": 0.7,
    "minOrder": 6,
    "price": 3880,
    "image": "images/80.jpg"
  },
  {
    "id": 81,
    "category": "Водка",
    "country": "Украина",
    "brand": "Celsius",
    "name": "Водка особая Celsius Ice",
    "volume": 1,
    "minOrder": 6,
    "price": 5250,
    "image": "images/81.jpg"
  },
  {
    "id": 82,
    "category": "Водка",
    "country": "Украина",
    "brand": "Celsius",
    "name": "Водка Celsius Classic",
    "volume": 0.5,
    "minOrder": 6,
    "price": 2750,
    "image": "images/82.jpg"
  },
  {
    "id": 83,
    "category": "Водка",
    "country": "Украина",
    "brand": "Celsius",
    "name": "Водка Celsius Classic",
    "volume": 0.7,
    "minOrder": 6,
    "price": 3670,
    "image": "images/83.jpg"
  },
  {
    "id": 84,
    "category": "Водка",
    "country": "Украина",
    "brand": "Celsius",
    "name": "Водка Celsius Classic",
    "volume": 1,
    "minOrder": 6,
    "price": 4920,
    "image": "images/84.jpg"
  },
  {
    "id": 85,
    "category": "Водка",
    "country": "Украина",
    "brand": "Celsius",
    "name": "Водка Celsius Original",
    "volume": 0.5,
    "minOrder": 6,
    "price": 2750,
    "image": "images/85.jpg"
  },
  {
    "id": 86,
    "category": "Водка",
    "country": "Украина",
    "brand": "Celsius",
    "name": "Водка Celsius Original",
    "volume": 0.7,
    "minOrder": 6,
    "price": 3670,
    "image": "images/86.jpg"
  }
];

const CATEGORY_META = {
  'Вино':   { icon: '🍷', title: 'Вино' },
  'Виски':  { icon: '🥃', title: 'Виски' },
  'Водка':  { icon: '🍾', title: 'Водка' }
};

const COUNTRY_META = {
  'Грузия':   { flag: '🇬🇪', title: 'Грузия' },
  'Италия':   { flag: '🇮🇹', title: 'Италия' },
  'Франция':  { flag: '🇫🇷', title: 'Франция' },
  'Ирландия': { flag: '🇮🇪', title: 'Ирландия' },
  'Россия':   { flag: '🇷🇺', title: 'Россия' },
  'Украина':  { flag: '🇺🇦', title: 'Украина' }
};

const CURRENCY = '₸';
